### ISSUE TITLE
EmberConf 2016?

### ISSUE THREAD

**Issue by ianvanness** [zurt/notes#21]
Kurt, any chance that you were in attendance for EmberConf 2016? I was there, and took plenty of notes, and I see that [poteto](https://github.com/poteto/emberconf-2016) did as well, but I've enjoyed your notes over the past two EmberConf's. If you weren't in attendance, or are no longer allowed to publicly share your notes, please feel free to close this "issue" (I couldn't find any other way to get in touch with you).

Many Thanks!

**Comment by zurt** [comment]
Sadly I couldn't go this year. Thanks for reaching out though. I look forward to watching the videos when they come out! Cheers.
